name:                sql-lesson
version:             0.1.0.0
github:              "MikeMKH/sql-lesson"
license:             BSD3
author:              "Mike Harris"
maintainer:          "@MikeMKH"
copyright:           "2020 Mike Harris"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MikeMKH/sql-lesson#readme>

dependencies:
- base >= 4.7 && < 5
- time
- sqlite-simple >= 0.4

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings

executables:
  sql-lesson-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sql-lesson

tests:
  sql-lesson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sql-lesson
